version: '3'

services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.11.1
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        aliases:
        - envoy
    expose:
    - "80"
    - "9901"
    ports:
    - "80:80"
    - "9901:9901"
  service_blue:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - service_blue
          - myservice
    environment:
      - SERVICE_NAME=blue
    expose:
      - "80"

  service_green:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - service_green
          - myservice
    environment:
      - SERVICE_NAME=green
    expose:
      - "80"

  service_red:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - service_red
          - myservice
    environment:
      - SERVICE_NAME=red
    expose:
      - "80"

networks:
  envoymesh: {}
