version: '3'

services:
  front-envoy:
    build:
      context: .
      dockerfile: ./Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "9901"
    ports:
      - "8080:80"
      - "9901:9901"
  service1:
    build:
      context: .
      dockerfile: ./Dockerfile-service
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80" 
  service2:
    build:
      context: .
      dockerfile: ./Dockerfile-service
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80" 

networks:
  envoymesh: {}
